# File: .github/workflows/workflow.yml

#============================================================================================
#      FILE NAME: Packer.yml
#      USAGE: Runs packer template code to create the image
#      VERSION: 1.0
#      AUTHOR: Sivalakshmana Kumar Koliseti
#      DEPARTMENT: Platform Team
#============================================================================================

on:
  workflow_dispatch:

name: Packer deployment Windows

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      #- name: Fix Template
       # uses: hashicorp/packer-github-actions@master
        #with:
         # command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: PackerWindow10Pro.pkr.hcl



      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          PKR_VAR_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          PKR_VAR_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          PKR_VAR_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
          target: PackerWindow10Pro.pkr.hcl
          var-file: variable.pkrvars.hcl
          working_directory: '.'
        env:
          PACKER_LOG: 1
          #HCP_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          #HCP_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SCERET }}
